### ISSUE TITLE
Pod Installation Error

### ISSUE THREAD

**Issue by tapannathvani** [neemssoni/rn-twilio-webrtc-app#1]
Error : 
```
[!] CocoaPods could not find compatible versions for pod "react-native-twilio-video-webrtc":
  In Podfile:
    react-native-twilio-video-webrtc (from `../node_modules/react-native-twilio-video-webrtc`)

Specs satisfying the `react-native-twilio-video-webrtc (from `../node_modules/react-native-twilio-video-webrtc`)` dependency were found, but they required a higher minimum deployment target.

```

I have set deployment target 12.0 in XCode.

Can you please help me to resolve it or do you have any other source to integrate twilio in react native application

**Comment by neemssoni** [comment]
Please set your minimum target version to 11.0, in Podfile also and for deployment target also. It will work for you.

**Comment by tapannathvani** [comment]
I have set 12.0 in podfile also.. and pod installation working. Thanks
